name: chnqoo_diary_mobile
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bot_toast: 4.0.4
  flutter_screenutil: ^5.9.0
  dio: 5.3.2
  # pretty_dio_logger: ^1.3.1
  logger: ^2.0.1
  provider: ^6.0.5
  hive: 2.2.3
  cupertino_icons: ^1.0.6
  flutter_pretty_dio_logger: ^3.0.0
  path_provider: ^2.1.2
  get: ^4.6.6
  carousel_slider: ^4.2.1
  flutter_speed_dial: ^7.0.0
  badges: ^3.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true